In [2]:
import torch
from torch import nn
import torch.nn.functional as F


In [8]:
# shapes of torch tensors
# ---------------------------

j = 0

print("%d --------- \n" % j)
i = torch.arange(10).resize_(1)
print(i)
print(i.shape)

j += 1
print("\n%d --------- \n" %j)
i = torch.arange(10).resize_(1,1)
print(i)
print(i.shape)

j += 1
print("\n%d --------- \n" %j)
i = torch.arange(10).resize_(0)
print(i)
print(i.shape)

j += 1
print("\n%d --------- \n" %j)
i = torch.arange(10).resize_(2,3)
print(i)
print(i.shape)

0 --------- 

tensor([0])
torch.Size([1])

1 --------- 

tensor([[0]])
torch.Size([1, 1])

2 --------- 

tensor([], dtype=torch.int64)
torch.Size([0])

3 --------- 

tensor([[0, 1, 2],
        [3, 4, 5]])
torch.Size([2, 3])


In [2]:
# SoftMax
# -----------------
# input is of size N x C = 1 
input1 = torch.tensor([0,0,0], requires_grad=True, dtype=torch.float)
print("input1.shape {}".format(input1.shape))
m_smx = nn.Softmax(dim=0)
print("softmax: {} ".format(m_smx(input1)))

print("\n")

# input is of size N x C = 1 
input1 = torch.tensor([0,1,1], requires_grad=True, dtype=torch.float)
print("input1.shape {}".format(input1.shape))
m_smx = nn.Softmax(dim=0)
print("softmax: {} ".format(m_smx(input1)))

print("\n")

# input is of size N x C = 1 x 3
input1 = torch.tensor([[0,1,1]], requires_grad=True, dtype=torch.float)
print("input1.shape {}".format(input1.shape))
m_smx = nn.Softmax(dim=1)
print("softmax: {} ".format(m_smx(input1)))



input1.shape torch.Size([3])
softmax: tensor([0.3333, 0.3333, 0.3333], grad_fn=<SoftmaxBackward>) 


input1.shape torch.Size([3])
softmax: tensor([0.1554, 0.4223, 0.4223], grad_fn=<SoftmaxBackward>) 


input1.shape torch.Size([1, 3])
softmax: tensor([[0.1554, 0.4223, 0.4223]], grad_fn=<SoftmaxBackward>) 


In [3]:
# LogSoftMax
# -----------------
# input is of size N x C = 1 
input2 = torch.tensor([0,0,0], requires_grad=True, dtype=torch.float)
print("input2.shape {}".format(input2.shape))
m_log_smx = nn.LogSoftmax(dim=0)
print("log softmax: {} ".format(m_log_smx(input2)))

print("\n")

# input is of size N x C = 1
input2 = torch.tensor([0,1,1], requires_grad=True, dtype=torch.float)
print("input2.shape {}".format(input2.shape))
m_log_smx = nn.LogSoftmax(dim=0)
print("log softmax: {} ".format(m_log_smx(input2)))

input2.shape torch.Size([3])
log softmax: tensor([-1.0986, -1.0986, -1.0986], grad_fn=<LogSoftmaxBackward>) 


input2.shape torch.Size([3])
log softmax: tensor([-1.8620, -0.8620, -0.8620], grad_fn=<LogSoftmaxBackward>) 


In [4]:
# Convert LogSoftMax output into SoftMax
# -------------------------
input3 = torch.tensor([-1.0986, -1.0986, -1.0986])
print(torch.exp(input3))

tensor([0.3333, 0.3333, 0.3333])


In [2]:
# topk
# ----------------
x = torch.arange(0,10).resize_((2,5))
print ("X: {}".format(x))

# topk => the top 2 values in the rows 
topk, indices = torch.topk(x,2)
print("topk: {}".format(topk))
print("indices: {}".format(indices))



X: tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
topk: tensor([[4, 3],
        [9, 8]])
indices: tensor([[4, 3],
        [4, 3]])


In [ ]:
# Slicing and zip
# ---------------
l = [512, 256, 128]
print(l[:-1])     # begin:end-1
print(l[1:])      # begin+1:end
layer_sizes = zip(l[:-1], l[1:])
[print("h1, h2: {}, {}".format(h1, h2)) for h1, h2 in layer_sizes]

[512, 256]
[256, 128]
h1, h2: 512, 256
h1, h2: 256, 128


[None, None]

In [2]:
# max
# --------------------------
import torch

x = torch.arange(0,10).resize_((2,5))
print ("X: {}".format(x))
print ("X.shape: {}".format(x.shape))

print("\n")

# Returns the max in each row for given dim
max, index = x.max(1)

print("max: {}".format(max))
print("index: {}".format(index))
print(max[1])

print("\n")

# Returns the max in each column (by collapsing dim 0 (rows)) for given dim
max, index = x.max(0)
print("max: {}".format(max))
print("index: {}".format(index))
print(max[1])


X: tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
X.shape: torch.Size([2, 5])


max: tensor([5, 6, 7, 8, 9])
index: tensor([1, 1, 1, 1, 1])
tensor(6)


In [18]:
# numpy max vs torch max
# --------------------------

import numpy as np

x = np.random.randn(3, 3)
print (x)
print(x.max(1))

print("\n")

print(torch.from_numpy(x).max(1))
# [0] => max values
# [1] => indices of max values
print(torch.from_numpy(x).max(1)[0])

[[-0.41916509 -0.49870665  1.63070857]
 [ 1.21679659 -0.5698281  -1.16761079]
 [-1.18229229 -0.84897776 -1.89130183]]
[ 1.63070857  1.21679659 -0.84897776]


torch.return_types.max(
values=tensor([ 1.6307,  1.2168, -0.8490], dtype=torch.float64),
indices=tensor([2, 0, 1]))
tensor([ 1.6307,  1.2168, -0.8490], dtype=torch.float64)
